# Generated by Django 3.2.9 on 2021-11-04 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 20, 42, 23, 172149)),
        ),
    ]
